import matplotlib

# matplotlib.use("Agg")

from .utils import (
    Hz_t,
    dB_t,
    dBm_t,
    m_t,
    deg_t,
    kelvin_t,
    GHz,
    MHz,
    kHz,
    Hz,
    dB,
    dBm,
    watt_to_dBm,
    m,
    dm,
    hm,
    km,
    degree,
    radians,
    to_radians,
    kelvin,
    celsius,
    to_celsius,
    EARTH_RADIUS,
)
from .physics import distance_max, Orbit
from .core import Element, Budget
from .elements import (
    Antenna,
    NPort,
    TwoPortsElement,
    Amplifier,
    Loss,
    PathLoss,
    ConverterType,
    Modulator,
    Filter,
    BandpassFilter,
    ButterworthBandpassFilter,
    filter,
)
from .propagation import (
    FreeSpacePathLossFriis,
    RadarFreeSpaceBasicLoss,
    OkumuraHataPathLoss,
    CostHataPathLoss,
)
from .visualizer import into_schemdraw

budget = Budget

__all__ = [
    "Hz_t",
    "dB_t",
    "dBm_t",
    "m_t",
    "deg_t",
    "kelvin_t",
    "GHz",
    "MHz",
    "kHz",
    "Hz",
    "dB",
    "dBm",
    "watt_to_dBm",
    "m",
    "dm",
    "hm",
    "km",
    "degree",
    "radians",
    "to_radians",
    "kelvin",
    "celsius",
    "to_celsius",
    "EARTH_RADIUS",
    "distance_max",
    "Orbit",
    "Element",
    "Budget",
    "Antenna",
    "NPort",
    "TwoPortsElement",
    "Amplifier",
    "Loss",
    "PathLoss",
    "ConverterType",
    "Modulator",
    "Filter",
    "BandpassFilter",
    "ButterworthBandpassFilter",
    "filter",
    "FreeSpacePathLossFriis",
    "RadarFreeSpaceBasicLoss",
    "OkumuraHataPathLoss",
    "CostHataPathLoss",
    "into_schemdraw",
    "budget",
]
